from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

# --------------------------------------------------------------------------- #
# Templates                                                                   #
# --------------------------------------------------------------------------- #

_PIPELINE_PY = '''\
"""
{name} — generated by `baton new`

Hierarchy: {hierarchy_str}
Edit the schemas, stages, and checkpoints to match your use case.
Run:  python pipeline.py
"""

from pydantic import BaseModel
from pipeline_builder import Pipeline, State, CheckpointResult, MockAIAdapter


# ── 1. Define one schema per hierarchy level ────────────────────────────────

class {class_0}(BaseModel):
    name: str


class {class_1}(BaseModel):
    source: str
    action: str


# ── 2. Create the pipeline ───────────────────────────────────────────────────

pipe = Pipeline(
    name="{name}",
    hierarchy={hierarchy!r},
    schemas={{{schema_map}}},
)


# ── 3. Stages ────────────────────────────────────────────────────────────────

@pipe.stage(reads=["{level_0}"], writes=["{level_1}"])
def expand(item: {class_0}, state: State, ai: MockAIAdapter) -> list[{class_1}]:
    """AI expands each {level_0} into one or more {level_1}s."""
    return [
        {class_1}(source=item.name, action=f"handle {{item.name}} — step A"),
        {class_1}(source=item.name, action=f"handle {{item.name}} — step B"),
    ]


# ── 4. Checkpoint ─────────────────────────────────────────────────────────────

@pipe.checkpoint(on_reject="expand", retry_limit=3)
def review(state: State) -> CheckpointResult:
    items = state.get_nodes("{level_1}")
    print(f"\\n--- Review: {{len(items)}} {level_1}(s) ---")
    for it in items:
        print(f"  {{it.action}}")
    answer = input("\\nConfirm? (y=confirm / n=reject): ").strip().lower()
    return CheckpointResult(action="confirm" if answer == "y" else "reject")


# ── 5. Run ────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    ai = MockAIAdapter()

    inputs = [
        {class_0}(name="alpha"),
        {class_0}(name="beta"),
    ]

    result = pipe.run(ai=ai, {level_0}=inputs)

    print(f"\\nDone  session={{result.session_id}}")
    print(f"  {{len(result.get_nodes(\'{level_1}\'))}} {level_1}(s) produced")
'''

_PYPROJECT_TOML = '''\
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["baton"]
'''


# --------------------------------------------------------------------------- #
# Commands                                                                    #
# --------------------------------------------------------------------------- #

def cmd_new(args: argparse.Namespace) -> int:
    name: str = args.name
    raw_hierarchy: list[str] = [h.strip() for h in args.hierarchy.split(",")]

    if len(raw_hierarchy) < 2:
        print("error: --hierarchy needs at least 2 levels, e.g. goal,task", file=sys.stderr)
        return 1

    dest = Path(name)
    if dest.exists():
        print(f"error: '{dest}' already exists", file=sys.stderr)
        return 1

    dest.mkdir(parents=True)

    level_0, level_1 = raw_hierarchy[0], raw_hierarchy[1]
    class_0, class_1 = level_0.capitalize(), level_1.capitalize()
    schema_map = ", ".join(f'"{h}": {h.capitalize()}' for h in raw_hierarchy[:2])
    hierarchy_str = " → ".join(raw_hierarchy)

    pipeline_src = _PIPELINE_PY.format(
        name=name,
        hierarchy=raw_hierarchy,
        hierarchy_str=hierarchy_str,
        level_0=level_0,
        level_1=level_1,
        class_0=class_0,
        class_1=class_1,
        schema_map=schema_map,
    )

    (dest / "pipeline.py").write_text(pipeline_src)
    (dest / "pyproject.toml").write_text(_PYPROJECT_TOML.format(name=name))

    print(textwrap.dedent(f"""\
        Created {dest}/
          pipeline.py     ← edit your stages here
          pyproject.toml

        Hierarchy: {hierarchy_str}

        Next steps:
          cd {name}
          python pipeline.py
    """))
    return 0


# --------------------------------------------------------------------------- #
# Entry point                                                                 #
# --------------------------------------------------------------------------- #

def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="baton",
        description="baton — code schedules, AI executes, state is truth",
    )
    sub = parser.add_subparsers(dest="command", metavar="<command>")

    # baton new
    p_new = sub.add_parser("new", help="scaffold a new baton project")
    p_new.add_argument("name", help="project name (used as directory)")
    p_new.add_argument(
        "--hierarchy",
        default="goal,task",
        metavar="LEVELS",
        help="comma-separated hierarchy levels (default: goal,task)",
    )

    args = parser.parse_args(argv)

    if args.command == "new":
        sys.exit(cmd_new(args))
    else:
        parser.print_help()
        sys.exit(0)


if __name__ == "__main__":
    main()
